### ISSUE TITLE
Issue in stack creation in AWS

### ISSUE THREAD

**Issue by RidmiR** [wso2/testgrid#1199]
**Description:**
Observing below issue when triggered a build for Ubuntu. Stack creation not completed within 60min. 

Cloudfomation stack status shows as below
`Failed to receive 1 resource signal(s) within the specified duration`

https://testgrid-live.private.wso2.com/admin/blue/organizations/jenkins/RELEASES%2Fintg-test-wso2ei-master/detail/intg-test-wso2ei-master/26/pipeline/177

```
[13:51:49,470] Error on infrastructure creation for deployment pattern 'DeploymentPattern{id='b72b0e14-c071-4fcb-a659-bd0e50d6b5f7', name='prod-wso2ei-intg-deployment', createdTimestamp='2019-03-29 12:31:10.0', modifiedTimestamp='2019-03-29 12:31:10.0', product='Product{id='bb8b1f8c-29b9-4fc1-a3a4-b26f901eb128', name='intg-test-wso2ei-master'}'}', in TestPlan org.wso2.testgrid.common.exception.TestGridInfrastructureException: Error occurred while waiting for stack prod-wso2ei-intg-deployment-flsh5x
	at org.wso2.testgrid.infrastructure.providers.AWSProvider.doProvision(AWSProvider.java:278)
	at org.wso2.testgrid.infrastructure.providers.AWSProvider.provision(AWSProvider.java:161)
	at org.wso2.testgrid.core.phase.InfraPhase.provisionInfrastructure(InfraPhase.java:108)
	at org.wso2.testgrid.core.phase.InfraPhase.executePhase(InfraPhase.java:73)
	at org.wso2.testgrid.core.phase.Phase.execute(Phase.java:60)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:83)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:280)at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:135)at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:130)
at org.wso2.testgrid.core.Main.main(Main.java:47)

Caused by: org.awaitility.core.ConditionTimeoutException: Condition org.wso2.testgrid.infrastructure.providers.aws.StackCreationWaiter$StackCreationVerifier was not fulfilled within 60 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:802)
	at org.wso2.testgrid.infrastructure.providers.aws.StackCreationWaiter.waitForStack(StackCreationWaiter.java:64)
	at org.wso2.testgrid.infrastructure.providers.AWSProvider.doProvision(AWSProvider.java:246)
	... 9 more
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kasunbg** [comment]
This is an issue with the userdata section of the cloudformation template you are using. This isn't a testgrid framework/deployment issue.

To further debug, we need to look at userdata logs. Please attach them here.
