### ISSUE TITLE
Shell executor output swallow the actual exception

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#477]
**Description:**

```
[2018-02-12 14:04:58,235] ERROR {org.wso2.testgrid.core.Main} - Error while executing command. org.wso2.testgrid.common.exception.CommandExecutionException: Unable to execute the TestPlan TestPlan{id='810c9abe-e21a-49dd-b614-6c47ae79db5f', status='FAIL', testRunNumber='2', createdTimestamp='', modifiedTimestamp='', deploymentPattern='DeploymentPattern{id='5f9db401-fc32-4010-9fb4-59911d62fc5d', name='pattern-2', createdTimestamp='2018-02-12 14:03:37.0', modifiedTimestamp='2018-02-12 14:03:37.0', product='Product{id='15e22ff4-be00-4dbf-9861-11e07eadef55', name='wso2is.local', createdTimestamp='2018-02-12 14:00:54.0', modifiedTimestamp='2018-02-12 14:00:54.0'}'}'}
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:254)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:134)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:119)
	at org.wso2.testgrid.core.Main.main(Main.java:49)
Caused by: org.wso2.testgrid.core.exception.TestPlanExecutorException: Exception occurred while running the deployment for deployment pattern 'DeploymentPattern{id='5f9db401-fc32-4010-9fb4-59911d62fc5d', name='pattern-2', createdTimestamp='2018-02-12 14:03:37.0', modifiedTimestamp='2018-02-12 14:03:37.0', product='Product{id='15e22ff4-be00-4dbf-9861-11e07eadef55', name='wso2is.local', createdTimestamp='2018-02-12 14:00:54.0', modifiedTimestamp='2018-02-12 14:00:54.0'}'}', in TestPlan
	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:105)
	at org.wso2.testgrid.core.TestPlanExecutor.runTestPlan(TestPlanExecutor.java:65)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:251)
	... 3 more
Caused by: org.wso2.testgrid.common.exception.TestGridDeployerException: Error occurred while executing the deploy script
	at org.wso2.testgrid.deployment.deployers.ShellDeployer.deploy(ShellDeployer.java:55)
	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:100)
	... 5 more
```

**Affected Product Version:**
0.9.0-m12

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
run-testplan against local-is-deployment test-scripts.

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
@yasassri can you provide your input please?
