### ISSUE TITLE
CmdLineException: "resolve-statuses" is not a valid value for "<sub-command>"

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#614]
**Description:**
Following error was noticed in IS build on testgrid-dev:

[11:08:03,038] Error while parsing command line arguments. org.kohsuke.args4j.CmdLineException: "resolve-statuses" is not a valid value for "<sub-command>"
	at org.kohsuke.args4j.spi.SubCommandHandler.fallback(SubCommandHandler.java:111)
	at org.kohsuke.args4j.spi.SubCommandHandler.parseArguments(SubCommandHandler.java:107)
	at org.kohsuke.args4j.CmdLineParser.parseArgument(CmdLineParser.java:520)
	at org.wso2.testgrid.core.Main.main(Main.java:43)

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
Noticed in IS for all combinations. 

**Steps to reproduce:**
Seems to be an issue in the Jenkinsfile.

**Related Issues:**

**Comment by harshanL** [comment]
This is fixed now.
