### ISSUE TITLE
java.lang.OutOfMemoryError error when executing the "generate-report" command

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#666]
**Description:**

Following exception can be observed in the TestGrid prod environment after all the test-plans have been executed and running the "generate-report" command to finalize the build.

Testgrid Home is set to :  /testgrid/testgrid-home
[33m[05:46:42,715] One or more database properties {DB_URL, DB_USER, DB_USER_PASS} are not set in config.properties. Using default properties in persistence.xml
[mLoading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Tue Apr 10 05:46:43 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Apr 10 05:46:43 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[32m[05:46:43,995] TestGrid Home	: /testgrid/testgrid-home
[m[32m[05:46:43,995] Finalizing testplans...
[m[Pipeline] sh
[wso2is-5.5.0-LTS] Running shell script
+ cd /testgrid/testgrid-home/testgrid-dist/WSO2-TestGrid
+ ./testgrid generate-report --product wso2is-5.5.0-LTS --groupBy scenario
__          _______  ____ ___    _______        _    _____      _     _ 
\ \        / / ____|/ __ \__ \  |__   __|      | |  / ____|    (_)   | |
 \ \  /\  / / (___ | |  | | ) |    | | ___  ___| |_| |  __ _ __ _  __| |
  \ \/  \/ / \___ \| |  | |/ /     | |/ _ \/ __| __| | |_ |  __| |/ _  |
   \  /\  /  ____) | |__| / /_     | |  __/\__ \ |_| |__| | |  | | (_| |
    \/  \/  |_____/ \____/____|    |_|\___||___/\__|\_____|_|  |_|\____|

Testgrid Home is set to :  /testgrid/testgrid-home
[32m[05:46:45,218] TestGrid Home	: /testgrid/testgrid-home
[m[32m[05:46:45,223] Generating test result report for wso2is-5.5.0-LTS
[m[33m[05:46:45,227] One or more database properties {DB_URL, DB_USER, DB_USER_PASS} are not set in config.properties. Using default properties in persistence.xml
[mLoading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Tue Apr 10 05:46:46 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Apr 10 05:46:46 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /testgrid/testgrid-home/testgrid-dist/WSO2-TestGrid/heap-dump.hprof ...
Unable to create /testgrid/testgrid-home/testgrid-dist/WSO2-TestGrid/heap-dump.hprof: File exists
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuffer.append(StringBuffer.java:270)
	at java.io.StringWriter.write(StringWriter.java:101)
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:130)
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:69)
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
	at com.github.mustachejava.codes.DefaultCode.run(DefaultCode.java:213)
	at com.github.mustachejava.codes.IterableCode.next(IterableCode.java:133)
	at com.github.mustachejava.reflect.BaseObjectHandler.iterate(BaseObjectHandler.java:85)
	at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:128)
	at com.github.mustachejava.codes.IterableCode.handle(IterableCode.java:54)
	at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:42)
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162)
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:55)
	at com.github.mustachejava.Mustache.execute(Mustache.java:38)
	at org.wso2.testgrid.reporting.renderer.MustacheTemplateRenderer.render(MustacheTemplateRenderer.java:42)
	at org.wso2.testgrid.reporting.model.Report.<init>(Report.java:68)
	at org.wso2.testgrid.reporting.TestReportEngine.generateReport(TestReportEngine.java:92)
	at org.wso2.testgrid.core.command.GenerateReportCommand.execute(GenerateReportCommand.java:71)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // ws
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: ABORTED

**Affected Product Version:**
0.9.0-m20

**Comment by kasunbg** [comment]
While we analyze the issue, I think we have to do the following to improve error handling.

1. Generate the heap-dump.hprof with the process-id appended instead of a static name. We can do this by JVM flags.
2. Provide Xmx 4GB per testgrid execution.  For Xms (minimum), 512m should be good enough since generate-test-plan etc. won't consume much memory.

WDYT?

**Comment by azinneera** [comment]
Changing the Xmx will not always resolve the issue IMO. This exception is thrown when we run just 8 test plans as well. 

This is happening due to the lengthy base64 encoded string given to the failure and passed icons in the report.

We can resolve this simply by switching to a font based icon system.
