### ISSUE TITLE
Error while running test-scripts/local-is-deployment via testgrid

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#727]
**Description:**

Following error was noticed when running the local-is-deployment via testgrid: `java.io.FileNotFoundException: /home/kasun/.testgrid/wso2is/01-local-is-deployment/d808171c-724c-3b2e-b0c7-7704b8e77282/1/deployment.json (No such file or directory)`

Full stack trace is as follows:
```
[2018-05-01 18:42:03,722]  INFO {org.wso2.testgrid.common.ShellExecutor} - Deployment has finished, test execution will commence next
[2018-05-01 18:42:03,725] ERROR {org.wso2.testgrid.common.Deployment} - /home/kasun/.testgrid/wso2is/01-local-is-deployment/d808171c-724c-3b2e-b0c7-7704b8e77282/1/deployment.json (No such file or directory)
[2018-05-01 18:42:03,741] ERROR {org.wso2.testgrid.core.TestPlanExecutor} - Exception occurred while running the deployment for deployment pattern 'DeploymentPattern{id='222f1f62-0d1b-4e7a-a8a3-32dc34c9ade7', name='01-local-is-deployment', createdTimestamp='2018-05-01 15:02:46.0', modifiedTimestamp='2018-05-01 15:02:46.0', product='Product{id='54498ca3-5646-45d8-a250-4176ef88a90c', name='wso2is', createdTimestamp='2018-05-01 14:57:26.0', modifiedTimestamp='2018-05-01 14:57:26.0'}'}', in TestPlan org.wso2.testgrid.common.exception.TestGridDeployerException: Error occurred while reading /home/kasun/.testgrid/wso2is/01-local-is-deployment/d808171c-724c-3b2e-b0c7-7704b8e77282/1/deployment.json
java.io.FileNotFoundException: /home/kasun/.testgrid/wso2is/01-local-is-deployment/d808171c-724c-3b2e-b0c7-7704b8e77282/1/deployment.json (No such file or directory)
	at org.wso2.testgrid.deployment.DeploymentUtil.getDeploymentCreationResult(DeploymentUtil.java:77)
	at org.wso2.testgrid.deployment.deployers.ShellDeployer.deploy(ShellDeployer.java:96)
	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:164)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:86)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:227)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:121)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)

[2018-05-01 18:42:03,769] ERROR {org.wso2.testgrid.core.TestPlanExecutor} - Error occurred while performing deployment for test planc0f8cb30-922b-441c-a9df-12bd25aef87fReleasing infrastructure...
[2018-05-01 18:42:03,770] ERROR {org.wso2.testgrid.core.TestPlanExecutor} - Execution of previous steps failed. Trying to release the possibly provisioned infrastructure
[2018-05-01 18:42:03,771]  INFO {org.wso2.testgrid.infrastructure.providers.ShellScriptProvider} - Destroying test environment...
[2018-05-01 18:42:03,784]  INFO {org.wso2.testgrid.common.ShellExecutor} - This is a Dummy Infrastructure destroy scripts!!
[2018-05-01 18:42:03,786]  INFO {org.wso2.testgrid.common.ShellExecutor} - Stopping and cleaning the IS server
[2018-05-01 18:42:03,784] INFO {org.wso2.testgrid.common.ShellExecutor} - + echo 'This is a Dummy Infrastructure destroy scripts!!'
[2018-05-01 18:42:03,797] INFO {org.wso2.testgrid.common.ShellExecutor} - + echo 'Stopping and cleaning the IS server'
[2018-05-01 18:42:03,798] INFO {org.wso2.testgrid.common.ShellExecutor} - + bash ./wso2is-5.4.0/bin/wso2server.sh stop
[2018-05-01 18:42:03,798] INFO {org.wso2.testgrid.common.ShellExecutor} - bash: ./wso2is-5.4.0/bin/wso2server.sh: No such file or directory
[2018-05-01 18:42:03,799] INFO {org.wso2.testgrid.common.ShellExecutor} - + rm -rf wso2is-5.4.0
```

**Affected Product Version:**
0.9.0-m23

**OS, DB, other environment details and versions:**    
Ubuntu 16.04
test-scripts/local-is-deployment/

**Steps to reproduce:**
Execute run-testplan.

**Related Issues:**
N/A

**Comment by pasindujw** [comment]
This has been fixed already to avoid occurring a FileNotFoundException. https://github.com/wso2/testgrid/blob/6f2e7a276f33fb3a1ebae44e37d43eb4dd76f566/deployment/src/main/java/org/wso2/testgrid/deployment/DeploymentUtil.java#L57

Hence we can close this. @lasanthaDLPDS

**Comment by lasanthaDLPDS** [comment]
As per the above comment, close the issue.
