### ISSUE TITLE
Handle Jmeter test scripts that does not generate JTLs

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#744]
**Description:**
With the new externalized jmeter impl, testgrid has provided the complete ownership of test scripts to test writers. Now, we have a problem case where a test script may not contain a Jmeter listener to dump JTLs. Testgrid will silently hide those. That means the final report testgrid produces may become unreliable.

So, we need a mechanism to circumvent this. Some options include:

1. Validate and fail if a jmeter script does not contain a JTL listener.
2. Inject a jmeter listener by pre-processing the jmeter scripts.

**Affected Product Version:**
0.9.0-m25

**OS, DB, other environment details and versions:**    
N/A

**Related Issues:**
N/A

**Comment by kasunbg** [comment]
This is the error message I got when the JTL was not generated:

```
[18:40:15,845] Error occurred while executing the SolutionPattern 'Test scenario 01' in TestPlan
Caused by java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.wso2.testgrid.automation.parser.JMeterResultParserFactory.getParser(JMeterResultParserFactory.java:56)
	at org.wso2.testgrid.automation.executor.JMeterExecutor.execute(JMeterExecutor.java:72)
	at org.wso2.testgrid.automation.Test.execute(Test.java:152)
	at org.wso2.testgrid.core.ScenarioExecutor.execute(ScenarioExecutor.java:96)
	at org.wso2.testgrid.core.TestPlanExecutor.runScenarioTests(TestPlanExecutor.java:142)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:111)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:227)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:121)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)

```

**Comment by harshanL** [comment]
This null pointer exception has fixed with commit https://github.com/wso2/testgrid/pull/751/commits/b808603b07dac8df4fd582ece6c093343c20cfbd

**Comment by pasindujw** [comment]
@harshanL Can we close this?

**Comment by harshanL** [comment]
+1. Let's close it.
