### ISSUE TITLE
Errors thrown during is-5.5.0 build.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#785]
**Description:**

Following errors were noticed in the wso2is-5.5.0-LTS job's build #26. Most of them seem to be real issues that we need to fix from testgrid side.

```
[main] INFO org.wso2.testgrid.automation.executor.JMeterExecutor - JMETER_HOME: /testgrid/apache-jmeter-3.3
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - working directory : /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter/21-pre-scenario-steps.sh: 35: /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter/21-pre-scenario-steps.sh: source: not found
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - pre-steps are done...
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - Created the tree successfully using jmeter/01-Scenario-21-EnforceUsersToProvideMissingRequiredAttributesWhileGettingJITProvisioned.jmx
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - Starting the test @ Thu Jun 07 07:14:03 UTC 2018 (1528355643191)
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - org.openqa.selenium.WebDriverException: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - System info: host: 'ip-172-31-84-235', ip: '172.31.84.235', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-135-generic', java.version: '1.8.0_161'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Driver info: driver.version: HtmlUnitDriver
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:554)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:530)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.reflect.Method.invoke(Method.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeMethod(Reflect.java:134)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeObjectMethod(Reflect.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Name.invokeMethod(Name.java:858)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.evalBlock(BSHBlock.java:130)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHTryStatement.eval(BSHTryStatement.java:86)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:645)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:739)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:728)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:222)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:69)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:424)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:255)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.Thread.run(Thread.java:748)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:176)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebRequest.getUrl(WebRequest.java:99)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:308)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:541)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 27 more
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator.toNormalUrl(URLCreator.java:40)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator$URLCreatorStandard.toUrlUnsafeClassic(URLCreator.java:71)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlUnsafe(UrlUtils.java:194)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:172)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 31 more
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - org.openqa.selenium.WebDriverException: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - System info: host: 'ip-172-31-84-235', ip: '172.31.84.235', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-135-generic', java.version: '1.8.0_161'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Driver info: driver.version: HtmlUnitDriver
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:554)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:530)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.reflect.Method.invoke(Method.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeMethod(Reflect.java:134)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeObjectMethod(Reflect.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Name.invokeMethod(Name.java:858)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.evalBlock(BSHBlock.java:130)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHTryStatement.eval(BSHTryStatement.java:86)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:645)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:739)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:728)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:222)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:69)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:424)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:255)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.Thread.run(Thread.java:748)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:176)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebRequest.getUrl(WebRequest.java:99)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:308)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:541)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 27 more
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator.toNormalUrl(URLCreator.java:40)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator$URLCreatorStandard.toUrlUnsafeClassic(URLCreator.java:71)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlUnsafe(UrlUtils.java:194)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:172)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 31 more
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - org.openqa.selenium.WebDriverException: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - System info: host: 'ip-172-31-84-235', ip: '172.31.84.235', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-135-generic', java.version: '1.8.0_161'
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Driver info: driver.version: HtmlUnitDriver
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:554)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:530)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.reflect.Method.invoke(Method.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeMethod(Reflect.java:134)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Reflect.invokeObjectMethod(Reflect.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Name.invokeMethod(Name.java:858)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:75)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.evalBlock(BSHBlock.java:130)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:80)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHBlock.eval(BSHBlock.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.BSHTryStatement.eval(BSHTryStatement.java:86)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:645)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:739)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.Interpreter.eval(Interpreter.java:728)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:222)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:69)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:498)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:424)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:255)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at java.lang.Thread.run(Thread.java:748)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.lang.RuntimeException: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:176)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebRequest.getUrl(WebRequest.java:99)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:308)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:541)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 27 more
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - Caused by: java.net.MalformedURLException: Missing host name in url: http://:/travelocity.com/index.jsp
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator.toNormalUrl(URLCreator.java:40)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.URLCreator$URLCreatorStandard.toUrlUnsafeClassic(URLCreator.java:71)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlUnsafe(UrlUtils.java:194)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	at com.gargoylesoftware.htmlunit.util.UrlUtils.toUrlSafe(UrlUtils.java:172)
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - 	... 31 more
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - Tidying up ...    @ Thu Jun 07 07:14:12 UTC 2018 (1528355652998)
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - ... end of run
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - working directory : /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter
[pool-20-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - post-steps are done...
[pool-20-thread-2] ERROR org.wso2.testgrid.common.ShellExecutor - /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter/21-post-scenario-steps.sh: 22: /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter/21-post-scenario-steps.sh: source: not found
[main] ERROR org.wso2.testgrid.automation.Test - Error occurred while executing the SolutionPattern 'scenario21' in TestPlan
Caused by 
org.wso2.testgrid.automation.TestAutomationException: Unable to parse the JMeter results file.
	at org.wso2.testgrid.automation.executor.JMeterExecutor.execute(JMeterExecutor.java:91)
	at org.wso2.testgrid.automation.Test.execute(Test.java:155)
	at org.wso2.testgrid.core.ScenarioExecutor.execute(ScenarioExecutor.java:117)
	at org.wso2.testgrid.core.TestPlanExecutor.runScenarioTests(TestPlanExecutor.java:195)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:164)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:227)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:121)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
Caused by: org.wso2.testgrid.automation.parser.JMeterResultParserException: Unable to locate the results jtl file in the directory : '/testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21'
	at org.wso2.testgrid.automation.parser.JMeterParserUtil.getJTLFile(JMeterParserUtil.java:47)
	at org.wso2.testgrid.automation.parser.JMeterResultParserFactory.getParser(JMeterResultParserFactory.java:61)
	at org.wso2.testgrid.automation.executor.JMeterExecutor.execute(JMeterExecutor.java:78)
	... 8 more
[pool-21-thread-1] INFO org.wso2.testgrid.common.ShellExecutor - working directory : /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/workspace/identity-test-integration/scenario21/jmeter
```

**Affected Product Version:**
m29

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kasunbg** [comment]
This actually has multiple issues. We may need to break down the tasks..

**Comment by pasindujw** [comment]
This is fixed.
