### ISSUE TITLE
WSO2 IS 5.5.0 product doesn't start for Ubuntu 16.04 / Open JDK9 / MySQL 5.7

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#794]
**Description:**

Noticed the below log for following infrastructure combination:

Infrastructure: {OSVersion=16.04, JDK=OPEN_JDK9, DBEngineVersion=5.7, OS=UBUNTU, DBEngine=mysql}

The AWS infrastructure provisioning was a success. But, for some reason, the product doesn't seem to start-up properly.

```
+ ./testgrid run-testplan --product wso2is-5.5.0-LTS --file /testgrid/testgrid-home/jobs/wso2is-5.5.0-LTS/test-plans/test-plan-03.yaml
__          _______  ____ ___    _______        _    _____      _     _ 
\ \        / / ____|/ __ \__ \  |__   __|      | |  / ____|    (_)   | |
 \ \  /\  / / (___ | |  | | ) |    | | ___  ___| |_| |  __ _ __ _  __| |
  \ \/  \/ / \___ \| |  | |/ /     | |/ _ \/ __| __| | |_ |  __| |/ _  |
   \  /\  /  ____) | |__| / /_     | |  __/\__ \ |_| |__| | |  | | (_| |
    \/  \/  |_____/ \____/____|    |_|\___||___/\__|\_____|_|  |_|\____|

Testgrid Home is set to :  /testgrid/testgrid-home
[33m[13:23:55,225] One or more database properties {DB_URL, DB_USER, DB_USER_PASS} are not set in config.properties. Using default properties in persistence.xml
[mLoading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Fri Jun 08 13:23:56 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Fri Jun 08 13:23:56 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[32m[13:23:56,399] TestGrid Home	: /testgrid/testgrid-home
[m[32m[13:23:57,462] Creating CloudFormation Stack 'infra-for-single-node-deployment-J5XO0O' in region 'us-east-1'. Script : pattern-1-with-puppet-cloudformation.template.yml
[m[32m[13:23:57,796] Waiting for stack : infra-for-single-node-deployment-J5XO0O, Infrastructure: {OSVersion=16.04, JDK=OPEN_JDK9, DBEngineVersion=5.7, OS=UBUNTU, DBEngine=mysql}

[m[32m[13:29:58,902] Event Details: 
Status: CREATE_COMPLETE, Resource Type: AWS::CloudFormation::Stack, Logical ID: infra-for-single-node-deployment-J5XO0O, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::ElasticLoadBalancingV2::Listener, Logical ID: WSO2EnvISALBListener, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::Listener, Logical ID: WSO2EnvISALBListener, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::Listener, Logical ID: WSO2EnvISALBListener, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::ElasticLoadBalancingV2::TargetGroup, Logical ID: WSO2EnvISALBTargetGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::TargetGroup, Logical ID: WSO2EnvISALBTargetGroup, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::TargetGroup, Logical ID: WSO2EnvISALBTargetGroup, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvISInstance, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvISInstance, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvISInstance, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::RDS::DBInstance, Logical ID: WSO2EnvDBInstance, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Route, Logical ID: route2, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::ElasticLoadBalancingV2::LoadBalancer, Logical ID: WSO2EnvISApplicationLoadBalancer, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Route, Logical ID: route2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Route, Logical ID: route2, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::NatGateway, Logical ID: WSO2EnvNATGateway, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::EIPAssociation, Logical ID: WSO2EnvBastionEIPAssociation, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::EIPAssociation, Logical ID: WSO2EnvBastionEIPAssociation, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::EIPAssociation, Logical ID: WSO2EnvBastionEIPAssociation, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvBastionInstance, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl3, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute3, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute2, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Route, Logical ID: route1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::RDS::DBInstance, Logical ID: WSO2EnvDBInstance, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::RDS::DBInstance, Logical ID: WSO2EnvDBInstance, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl3, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::LoadBalancer, Logical ID: WSO2EnvISApplicationLoadBalancer, Status Reason: Resource creation Initiated
Status: CREATE_COMPLETE, Resource Type: AWS::RDS::DBSubnetGroup, Logical ID: WSO2EnvDBSubnetGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl3, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute3, Status Reason: Resource creation Initiated
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::RDS::DBSubnetGroup, Logical ID: WSO2EnvDBSubnetGroup, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NatGateway, Logical ID: WSO2EnvNATGateway, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvBastionInstance, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::ElasticLoadBalancingV2::LoadBalancer, Logical ID: WSO2EnvISApplicationLoadBalancer, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NatGateway, Logical ID: WSO2EnvNATGateway, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::RDS::DBSubnetGroup, Logical ID: WSO2EnvDBSubnetGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute3, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Route, Logical ID: route1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetRouteTableAssociation, Logical ID: subnetroute1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SubnetNetworkAclAssociation, Logical ID: subnetacl2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Instance, Logical ID: WSO2EnvBastionInstance, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Route, Logical ID: route1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet2, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPrivateSubnet1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::VPCGatewayAttachment, Logical ID: gw1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvDBSecurityGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvDBSecurityGroup, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvDBSecurityGroup, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvInstanceSecurityGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvInstanceSecurityGroup, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvInstanceSecurityGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAclEntry, Logical ID: acl1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvLBSecurityGroup, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::NetworkAcl, Logical ID: WSO2EnvNetworkAcl, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvRouteTable2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvLBSecurityGroup, Status Reason: Resource creation Initiated
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvPublicRouteTable1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::VPCDHCPOptionsAssociation, Logical ID: dchpassoc1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAcl, Logical ID: WSO2EnvNetworkAcl, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvRouteTable2, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPCDHCPOptionsAssociation, Logical ID: dchpassoc1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPrivateSubnet1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::NetworkAcl, Logical ID: WSO2EnvNetworkAcl, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvRouteTable2, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::SecurityGroup, Logical ID: WSO2EnvLBSecurityGroup, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPCDHCPOptionsAssociation, Logical ID: dchpassoc1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPCGatewayAttachment, Logical ID: gw1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvPublicRouteTable1, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPublicSubnet1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPCGatewayAttachment, Logical ID: gw1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::Subnet, Logical ID: WSO2EnvPrivateSubnet1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::RouteTable, Logical ID: WSO2EnvPublicRouteTable1, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::VPC, Logical ID: WSO2EnvVPC, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::InternetGateway, Logical ID: WSO2EnvInternetGateway, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::EIP, Logical ID: WSO2EnvBastionEIP, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::DHCPOptions, Logical ID: WSO2EnvDHCPOptions, Status Reason: null
Status: CREATE_COMPLETE, Resource Type: AWS::EC2::EIP, Logical ID: WSO2EnvEIP1, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPC, Logical ID: WSO2EnvVPC, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::InternetGateway, Logical ID: WSO2EnvInternetGateway, Status Reason: Resource creation Initiated
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::VPC, Logical ID: WSO2EnvVPC, Status Reason: null
Status: CREATE_IN_PROGRESS, Resource Type: AWS::EC2::EIP, Logical ID: WSO2EnvBastionEIP, Status Reason: Resource creation Initiated

[m[32m[13:29:58,904] Stack : infra-for-single-node-deployment-J5XO0O, with ID : arn:aws:cloudformation:us-east-1:809489900555:stack/infra-for-single-node-deployment-J5XO0O/32cec510-6b1f-11e8-b438-50fae98b1835 creation completed !
[m[32m[13:29:58,942] Created a CloudFormation Stack with the name :infra-for-single-node-deployment-J5XO0O
[m[32m[13:29:58,945] Waiting for server start-up.. : is-single-node-deployment
[m[32m[13:29:58,946] Waiting for server startup on URL : https://identity-demo7IT1HK-1352426516.us-east-1.elb.amazonaws.com/carbon
[m[31m[14:30:09,167] Exception occurred while running the deployment for deployment pattern 'DeploymentPattern{id='108b6b65-e508-43fe-8380-be1a84903bfb', name='is-single-node-deployment', createdTimestamp='2018-04-09 12:13:07.0', modifiedTimestamp='2018-04-09 12:13:07.0', product='Product{id='d78a84aa-20b7-4ef8-8bd8-cf7b1efe41a8', name='wso2is-5.5.0-LTS', createdTimestamp='2018-04-09 11:29:27.0', modifiedTimestamp='2018-04-09 11:29:27.0'}'}', in TestPlan org.wso2.testgrid.common.exception.TestGridDeployerException: Timeout occurred while waiting for pattern : is-single-node-deploymentTimeout value : 60MINUTES
	at org.wso2.testgrid.deployment.deployers.AWSDeployer.deploy(AWSDeployer.java:82)
	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:164)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:86)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:225)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:119)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition org.wso2.testgrid.deployment.DeploymentValidator$AWSCallable was not fulfilled within 60 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:802)
	at org.wso2.testgrid.deployment.DeploymentValidator.waitForDeployment(DeploymentValidator.java:55)
	at org.wso2.testgrid.deployment.deployers.AWSDeployer.deploy(AWSDeployer.java:79)
	... 6 more

[m[31m[14:30:09,186] Error occurred while performing deployment for test plan5cf962f1-ad9a-45b7-ae8a-fff508fe40d1Releasing infrastructure...
[m[31m[14:30:09,186] Execution of previous steps failed. Trying to release the possibly provisioned infrastructure
[m[32m[14:30:09,294] Waiting for stack : infra-for-single-node-deployment-J5XO0O to delete..

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
m30

**OS, DB, other environment details and versions:**    
OSVersion=16.04, JDK=OPEN_JDK9, DBEngineVersion=5.7, OS=UBUNTU, DBEngine=mysql

**Steps to reproduce:**
We need to run the wso2 is 5.5.0 just for above infra combination and try to reproduce this.

Currently, the best way to run a job for a given infrastructure combination is to create a custom testgrid.yaml and set 'includes' tag under infrastructureConfig.

**Related Issues:**
#680

**Comment by harshanL** [comment]
I have checked the server startup and the issue has occurred due to OPENJDK 9 is not yet supported by the product (I believe the same issue will occur for other products as well). Given below is the console out when starting the product manually. 

Starting WSO2 Carbon (in unsupported JDK)
 [ERROR] CARBON is supported only on JDK 1.7 and 1.8
JAVA_HOME environment variable is set to /usr/java/openjdk-9.0.4
CARBON_HOME environment variable is set to /opt/wso2/wso2is-5.5.0
Using Java memory options: -Xms256m -Xmx1024m
-Djava.endorsed.dirs=/opt/wso2/wso2is-5.5.0/lib/endorsed:/usr/java/openjdk-9.0.4/jre/lib/endorsed:/usr/java/openjdk-9.0.4/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

However, as per the doc [1], I've tried removing *-Djava.endorsed.dirs* property and hit with another blocker in OSGi.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.internal.baseadaptor.BaseStorage (file:/opt/wso2/wso2is-5.5.0/repository/components/plugins/org.eclipse.osgi_3.9.1.v20130814-1242.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.baseadaptor.BaseStorage
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.RuntimeException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
	at org.wso2.carbon.server.CarbonLauncher.launch(CarbonLauncher.java:115)
	at org.wso2.carbon.server.Main.launchCarbon(Main.java:160)
	at org.wso2.carbon.server.Main.main(Main.java:94)
	... 6 more

[1]. https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-2C896CA8-927C-4381-A737-B1D81D964B7B
