### ISSUE TITLE
Tinkerer log download is broken

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#888]
**Description:**

Following error is noticed in the build: <tg_host>/admin/blue/organizations/jenkins/wso2am-intg/detail/wso2am-intg/191/pipeline/87/

```
[12:40:13,655] Downloading log file : TEST-TestSuite.xml
[12:40:13,666] Error while downloading the log files for TestPlanwso2am-intg org.wso2.testgrid.tinkerer.exception.TinkererOperationException: Error occurred deriving the destination path for logfile : TEST-TestSuite.xml
from agent :aws:us-east-1:8778a1a9-8538-4178-86f6-054d232a6c9b:i-0d60c491fd5e5ed10:18.209.55.63
Running on instance : wso2-apim-intg-node
for test plan :8778a1a9-8538-4178-86f6-054d232a6c9b
	at org.wso2.testgrid.tinkerer.UnixClient.downloadLogs(UnixClient.java:248)
	at org.wso2.testgrid.core.TestPlanExecutor.performPostTestPlanActions(TestPlanExecutor.java:179)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:145)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:231)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:119)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:126)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
Caused by: org.wso2.testgrid.tinkerer.exception.TinkererOperationException: Failed to download the file :/testgrid/testgrid-home/jobs/wso2am-intg/builds/integration-tests_feebd01d-f884-3644-b004-26ce98044bb0_19/TEST-TestSuite.xml
	at org.wso2.testgrid.tinkerer.UnixClient.downloadLogs(UnixClient.java:226)
	... 6 more
```

**Affected Product Version:**
m36

**OS, DB, other environment details and versions:**    
tg-dev

**Comment by pasindujw** [comment]
This is fixed.
