### ISSUE TITLE
NPE when running generate-email command locally

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#921]
**Description:**
Following NPE was noticed when running generate-email locally.

```
Exception in thread "main" java.lang.NullPointerException
	at org.wso2.testgrid.reporting.GraphDataProvider.processTestFailureSummary(GraphDataProvider.java:110)
	at org.wso2.testgrid.reporting.GraphDataProvider.getTestFailureSummary(GraphDataProvider.java:86)
	at org.wso2.testgrid.reporting.TestReportEngine.generateSummarizedEmailReport(TestReportEngine.java:851)
	at org.wso2.testgrid.core.command.GenerateEmailCommand.execute(GenerateEmailCommand.java:60)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:126)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
```

Seems the failure is at this line because OSVersion is not there in my local DB:
https://github.com/wso2/testgrid/blob/aececc64bf73dadcdd9eb295f9dcda734b767d6e/reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java#L109

DB content:
```sql
mysql> select * from infrastructure_parameter;
+------------+---------------------+---------------------+------------+-------------------------+--------------------+------+
| id         | created_timestamp   | modified_timestamp  | NAME       | PROPERTIES              | ready_for_testgrid | TYPE |
+------------+---------------------+---------------------+------------+-------------------------+--------------------+------+
| centos-7.4 | 2018-07-28 19:50:50 | 2018-07-28 19:50:50 | centos-7.4 | OS=CentOS,OSVersion=7.4 |                  1 | OS   |
+------------+---------------------+---------------------+------------+-------------------------+--------------------+------+
1 row in set (0.00 sec)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by azinneera** [comment]
Tested with an OS that is not in the database but this was not locally reproducible.
